language: node_js
node_js:
  - "8.9.0"
before_install:
  - echo -e "\n\nmachine github.com\n  login $GH_TOKEN\n" >~/.netrc
script:
  - "npm list"
  - "ls -l node_modules/"
  - "node node_modules/pxt-core/built/pxt.js travis"
sudo: false
cache:
  directories:
    - node_modules
